### ISSUE TITLE
doesnt compile on buster

### ISSUE THREAD

**Issue by tommybuck** [dnivanthaka/linux-am2320-driver#2]
Hi,

Trying to compile on raspbian buster (Linux 4.19.58-v7+ armv7l). I have installed kernel-headers package ( sudo apt-get install raspberrypi-kernel-headers)

I'm getting the following error when I run make:

make -C /lib/modules/4.19.58-v7+/build M=/home/pi/linux-am2320-driver modules
make[1]: Entering directory '/usr/src/linux-headers-4.19.58-v7+'
  CC [M]  /home/pi/linux-am2320-driver/am2320.o
/home/pi/linux-am2320-driver/am2320.c:127:5: error: initialization of ‘struct device_attribute *’ from incompatible pointer type ‘struct attribute *’ [-Werror=incompatible-pointer-types]
     &sensor_dev_attr_temp1_max.dev_attr.attr,
     ^
/home/pi/linux-am2320-driver/am2320.c:127:5: note: (near initialization for ‘am2320_attrs[0]’)
/home/pi/linux-am2320-driver/am2320.c:128:5: error: initialization of ‘struct device_attribute *’ from incompatible pointer type ‘struct attribute *’ [-Werror=incompatible-pointer-types]
     &sensor_dev_attr_temp1_min.dev_attr.attr,
     ^
/home/pi/linux-am2320-driver/am2320.c:128:5: note: (near initialization for ‘am2320_attrs[1]’)
/home/pi/linux-am2320-driver/am2320.c:129:5: error: initialization of ‘struct device_attribute *’ from incompatible pointer type ‘struct attribute *’ [-Werror=incompatible-pointer-types]
     &sensor_dev_attr_temp1_input.dev_attr.attr,
     ^
/home/pi/linux-am2320-driver/am2320.c:129:5: note: (near initialization for ‘am2320_attrs[2]’)
/home/pi/linux-am2320-driver/am2320.c:130:5: error: initialization of ‘struct device_attribute *’ from incompatible pointer type ‘struct attribute *’ [-Werror=incompatible-pointer-types]
     &sensor_dev_attr_humidity1_input.dev_attr.attr,
     ^
/home/pi/linux-am2320-driver/am2320.c:130:5: note: (near initialization for ‘am2320_attrs[3]’)
/home/pi/linux-am2320-driver/am2320.c:136:14: error: initialization of ‘struct attribute **’ from incompatible pointer type ‘struct device_attribute **’ [-Werror=incompatible-pointer-types]
     .attrs = am2320_attrs,
              ^~~~~~~~~~~~
/home/pi/linux-am2320-driver/am2320.c:136:14: note: (near initialization for ‘am2320_group.attrs’)
/home/pi/linux-am2320-driver/am2320.c: In function ‘am2320_i2c_probe’:
/home/pi/linux-am2320-driver/am2320.c:295:1: warning: label ‘err_free_res’ defined but not used [-Wunused-label]
 err_free_res:
 ^~~~~~~~~~~~
/home/pi/linux-am2320-driver/am2320.c:242:9: warning: unused variable ‘error’ [-Wunused-variable]
     int error;
         ^~~~~
/home/pi/linux-am2320-driver/am2320.c:241:9: warning: unused variable ‘ret’ [-Wunused-variable]
     int ret;
         ^~~
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:310: /home/pi/linux-am2320-driver/am2320.o] Error 1
make[1]: *** [Makefile:1517: _module_/home/pi/linux-am2320-driver] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.19.58-v7+'
make: *** [Makefile:4: all] Error 2

**Comment by maphilli14** [comment]
I think I have the same problem on RasperryPi4b:

`pi@astrocart:~/linux-am2320-driver $ make
make -C /lib/modules/5.10.17-v7l+/build M=/home/pi/linux-am2320-driver modules
make[1]: Entering directory '/home/pi/linux-623ca2ba45d86eb1b0323637330295c3f8d93c76'
  CC [M]  /home/pi/linux-am2320-driver/am2320.o
/home/pi/linux-am2320-driver/am2320.c:127:5: error: initialization of ‘struct device_attribute *’ from incompatible pointer type ‘struct attribute *’ [-Werror=incompatible-pointer-types]
     &sensor_dev_attr_temp1_max.dev_attr.attr,
     ^
/home/pi/linux-am2320-driver/am2320.c:127:5: note: (near initialization for ‘am2320_attrs[0]’)
/home/pi/linux-am2320-driver/am2320.c:128:5: error: initialization of ‘struct device_attribute *’ from incompatible pointer type ‘struct attribute *’ [-Werror=incompatible-pointer-types]
     &sensor_dev_attr_temp1_min.dev_attr.attr,
     ^
/home/pi/linux-am2320-driver/am2320.c:128:5: note: (near initialization for ‘am2320_attrs[1]’)
/home/pi/linux-am2320-driver/am2320.c:129:5: error: initialization of ‘struct device_attribute *’ from incompatible pointer type ‘struct attribute *’ [-Werror=incompatible-pointer-types]
     &sensor_dev_attr_temp1_input.dev_attr.attr,
     ^
/home/pi/linux-am2320-driver/am2320.c:129:5: note: (near initialization for ‘am2320_attrs[2]’)
/home/pi/linux-am2320-driver/am2320.c:130:5: error: initialization of ‘struct device_attribute *’ from incompatible pointer type ‘struct attribute *’ [-Werror=incompatible-pointer-types]
     &sensor_dev_attr_humidity1_input.dev_attr.attr,
     ^
/home/pi/linux-am2320-driver/am2320.c:130:5: note: (near initialization for ‘am2320_attrs[3]’)
/home/pi/linux-am2320-driver/am2320.c:136:14: error: initialization of ‘struct attribute **’ from incompatible pointer type ‘struct device_attribute **’ [-Werror=incompatible-pointer-types]
     .attrs = am2320_attrs,
              ^~~~~~~~~~~~
/home/pi/linux-am2320-driver/am2320.c:136:14: note: (near initialization for ‘am2320_group.attrs’)
/home/pi/linux-am2320-driver/am2320.c: In function ‘am2320_i2c_probe’:
/home/pi/linux-am2320-driver/am2320.c:295:1: warning: label ‘err_free_res’ defined but not used [-Wunused-label]
 err_free_res:
 ^~~~~~~~~~~~
/home/pi/linux-am2320-driver/am2320.c:242:9: warning: unused variable ‘error’ [-Wunused-variable]
     int error;
         ^~~~~
/home/pi/linux-am2320-driver/am2320.c:241:9: warning: unused variable ‘ret’ [-Wunused-variable]
     int ret;
         ^~~
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:279: /home/pi/linux-am2320-driver/am2320.o] Error 1
make[1]: *** [Makefile:1804: /home/pi/linux-am2320-driver] Error 2
make[1]: Leaving directory '/home/pi/linux-623ca2ba45d86eb1b0323637330295c3f8d93c76'
make: *** [Makefile:4: all] Error 2
`
